# Generated by Django 4.1.13 on 2024-03-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.TextField(max_length=225)),
                ('warehouse_capacity', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='gudang',
        ),
    ]
