# Generated by Django 4.1.13 on 2024-03-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_test', '0002_warehouse_delete_gudang'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(max_length=225)),
                ('product_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.TextField(choices=[('in', 'in'), ('out', 'out')], max_length=225)),
                ('wtransaction_date', models.DateTimeField()),
            ],
        ),
    ]
