# Generated by Django 4.1.13 on 2024-03-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_test', '0003_product_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='gudang',
            fields=[
                ('warehouse_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='gudang')),
                ('warehouse_name', models.TextField(max_length=225)),
                ('warehouse_capacity', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='warehouse',
        ),
    ]
