# Generated by Django 4.1.13 on 2024-03-27 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_test', '0005_produc_transactio_delete_product_delete_transaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='produc',
            new_name='product',
        ),
        migrations.RenameModel(
            old_name='transactio',
            new_name='transaction',
        ),
        migrations.RenameModel(
            old_name='gudang',
            new_name='warehouse',
        ),
    ]
