# Generated by Django 4.1.13 on 2024-03-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_test', '0007_produc_warehous_delete_product_delete_warehouse_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='produc',
            new_name='product',
        ),
        migrations.RenameModel(
            old_name='warehous',
            new_name='warehouse',
        ),
    ]
