# Generated by Django 4.1.13 on 2024-03-27 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_test', '0011_transactio_delete_transaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='transactio',
            new_name='transaction',
        ),
    ]
