# Generated by Django 4.1.13 on 2024-03-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_test', '0012_rename_transactio_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='wtransaction_date',
            new_name='transaction_date',
        ),
    ]
